"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#h@#ce)tel(31lm0vzejwvnwvl40oqhr2onuk(#%!olll7d1zm'


RAZORPAY_KEY_ID = 'rzp_test_S2y7e0HY3lpNIo'  # Get from Razorpay Dashboard
RAZORPAY_KEY_SECRET = '7P1bV1fk3s1E89zAbUGosqTQ'  # Get from Razorpay Dashboard

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
   

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',   #app is created...  app name want to give here
    'employer',
    'register',
    'employee',
    'chat_bot',
    'message_system',
    'admin_self',
    'voice_assistant',


    

]



# Voice Assistant Settings
VOICE_ASSISTANT_SETTINGS = {
    'ENABLED': True,
    'DEFAULT_VOICE': 'female',
    'SPEECH_RATE': 150,
    'LISTEN_TIMEOUT': 10,
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'employer.middleware.AccountStatusMiddleware',
    # 'home.middleware.ClearRegistrationDataMiddleware',
    # 'voice_assistant.apps.VoiceAssistantConfig',



]

ROOT_URLCONF = 'backend.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  #html file are created here folder name give here.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'employee.views.employee_notifications_processor',  # Added context processor
                'employer.context_processors.employer_notifications',  # Added employer context processor
                #this line is for media files
                'django.template.context_processors.media',
            ],
        },
    },
]

#web server gateway interface(wsgi)
#   in "asgi" multiple user can click same button at same time..... "in wsgi" single click at a time. in production time it will use
WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


#it is used to connect wit the xampp.. 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'jobportal_database',work_nest_data_base
        'NAME': 'work_nest_data_base',
        'USER': 'root',
        'PASSWORD':'',
        'HOST':'localhost',
        'PORT':'3306',
        'OPTION': {'init_command':"SET sql_mode='STRICT_TRSNS_TABLES'"}

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Add ML model path
ML_MODEL_PATH = os.path.join(BASE_DIR, 'xg_boost', 'complete_xgboost_package.pkl')

# Ensure the directory exists
XG_BOOST_DIR = os.path.join(BASE_DIR, 'xg_boost')
if not os.path.exists(XG_BOOST_DIR):
    os.makedirs(XG_BOOST_DIR)

    

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'    #css is load here
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]
STATIC_ROOT= os.path.join(BASE_DIR,'staticfiles')

# Media files (User uploaded files, profile photos)
MEDIA_URL = '/media/'  # Add this line
MEDIA_ROOT='/media/'     # files and profile photo will save here
MEDIA_ROOT= os.path.join(BASE_DIR,'media')

# File upload settings
FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]

# Max upload size (5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'home.User'




# === EMAIL CONFIGURATION 
# Add this section AFTER AUTH_USER_MODEL

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTP server
EMAIL_PORT = 587  # Port for TLS
EMAIL_USE_TLS = True  # Use TLS encryption
EMAIL_HOST_USER = 'your-email@gmail.com'  # place with my Gmail
EMAIL_HOST_PASSWORD = 'your-app-password'  # Replace with app password Select "Mail" → "Other" → Name it "Django App"
DEFAULT_FROM_EMAIL = 'noreply@skillconnect.com'  # "From" address
DEVELOPER_EMAIL = 'developer@skillconnect.com'  # Where support emails go





VOICE_ASSISTANT = {
    'ENABLED': True,
    'AUTO_START': True,  # Auto-start on page load
    'WAKE_WORDS': ['hello', 'hi', 'hey', 'assistant', 'വിളി', 'ഹലോ', 'ഹായ്'],
    'DEFAULT_LANGUAGE': 'en',
    'BASE_URL': 'http://localhost:8000',
}

# # Optional: Email timeout (seconds)
# EMAIL_TIMEOUT = 30