# Generated by Django 4.2 on 2026-02-01 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employer_profiles/')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('location_visibility', models.CharField(choices=[('full', 'Show full address to workers'), ('partial', 'Show only city and state to workers'), ('hidden', 'Hide location from workers')], default='partial', max_length=10)),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German')], default='english', max_length=20)),
                ('currency', models.CharField(choices=[('inr', 'Indian Rupee (₹)'), ('usd', 'US Dollar ($)'), ('eur', 'Euro (€)'), ('gbp', 'British Pound (£)')], default='inr', max_length=10)),
                ('timezone', models.CharField(choices=[('ist', 'India Standard Time (IST)'), ('est', 'Eastern Standard Time (EST)'), ('pst', 'Pacific Standard Time (PST)'), ('gmt', 'Greenwich Mean Time (GMT)')], default='ist', max_length=10)),
                ('date_format', models.CharField(choices=[('dd-mm-yyyy', 'DD-MM-YYYY'), ('mm-dd-yyyy', 'MM-DD-YYYY'), ('yyyy-mm-dd', 'YYYY-MM-DD')], default='dd-mm-yyyy', max_length=20)),
                ('two_factor_auth', models.BooleanField(default=True)),
                ('show_profile_to_workers', models.BooleanField(default=True)),
                ('data_sharing_analytics', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('marketing_communications', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=10)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employer_detail_table',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], default='razorpay', max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='employer.employer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='employee.jobrequest')),
            ],
            options={
                'db_table': 'payment_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('platform', 'Platform Experience'), ('payment', 'Payment Process'), ('support', 'Customer Support'), ('feature', 'Feature Request'), ('bug', 'Bug Report')], max_length=50)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('areas', models.JSONField(default=list)),
                ('recommendation', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_reviews', to='employer.employer')),
            ],
            options={
                'db_table': 'site_review_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('employee_issue', 'Employee Issue'), ('platform_issue', 'Platform Issue'), ('safety_concern', 'Safety Concern'), ('payment_dispute', 'Payment Dispute'), ('misconduct', 'Misconduct'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low - Minor issue'), ('medium', 'Medium - Needs attention'), ('high', 'High - Urgent attention needed'), ('critical', 'Critical - Immediate action required')], max_length=20)),
                ('resolution_preference', models.TextField(blank=True)),
                ('contact_methods', models.JSONField(default=list)),
                ('share_with_employee', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employer.employer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.jobrequest')),
            ],
            options={
                'db_table': 'report_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='payment_invoices/')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='employer.payment')),
            ],
            options={
                'db_table': 'payment_invoice_table',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployerNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System Message'), ('profile', 'Profile Update'), ('security', 'Security Alert'), ('payment', 'Payment Update'), ('job', 'Job Update')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employer.employer')),
            ],
            options={
                'db_table': 'employer_notification_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerLogin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='employer.employer')),
            ],
            options={
                'db_table': 'employer_login_table',
            },
        ),
        migrations.CreateModel(
            name='EmployerFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='employer.employer')),
            ],
            options={
                'db_table': 'employer_favorite_table',
                'ordering': ['-created_at'],
                'unique_together': {('employer', 'employee')},
            },
        ),
    ]
