# Generated by Django 5.2.5 on 2026-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='employer_documents/business/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='business_verified',
            field=models.BooleanField(default=False),
        ),
    ]
