# Generated by Django 5.2.5 on 2026-02-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employer_business_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='aadhar_document',
            field=models.FileField(blank=True, null=True, upload_to='employer_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='aadhar_upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='aadhar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
