# Generated by Django 4.2 on 2026-02-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Professional Title')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='City/Area')),
                ('bio', models.TextField(blank=True, help_text='Tell employers about your skills and experience', null=True)),
                ('years_experience', models.IntegerField(default=0, verbose_name='Years of Experience')),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma separated skills', null=True)),
                ('rating', models.FloatField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_jobs_done', models.IntegerField(default=0)),
                ('success_rate', models.IntegerField(default=0, verbose_name='Success Rate (%)')),
                ('availability_status', models.CharField(default='Currently Available', max_length=100)),
                ('response_time', models.CharField(default='Within 1 hour', max_length=50)),
                ('working_hours', models.CharField(default='9:00 AM - 7:00 PM', max_length=100)),
                ('service_area', models.CharField(default='Within 10 km radius', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('service_radius', models.IntegerField(choices=[(5, '5 km'), (10, '10 km'), (15, '15 km'), (20, '20 km'), (30, '30 km')], default=10)),
                ('two_factor_auth', models.BooleanField(default=True)),
                ('show_profile_to_employer', models.BooleanField(default=True)),
                ('share_work_history', models.BooleanField(default=True)),
                ('privacy_level', models.CharField(choices=[('full', 'Show full profile to employers'), ('partial', 'Show only basic information'), ('hidden', 'Hide profile from employers')], default='partial', max_length=10)),
                ('data_sharing_analytics', models.BooleanField(default=False)),
                ('job_alerts', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('payment_alerts', models.BooleanField(default=True)),
                ('platform_updates', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German')], default='english', max_length=20)),
                ('currency', models.CharField(choices=[('inr', 'Indian Rupee (₹)'), ('usd', 'US Dollar ($)'), ('eur', 'Euro (€)'), ('gbp', 'British Pound (£)')], default='inr', max_length=10)),
                ('timezone', models.CharField(choices=[('ist', 'India Standard Time (IST)'), ('est', 'Eastern Standard Time (EST)'), ('pst', 'Pacific Standard Time (PST)'), ('gmt', 'Greenwich Mean Time (GMT)')], default='ist', max_length=10)),
                ('date_format', models.CharField(choices=[('dd-mm-yyyy', 'DD-MM-YYYY'), ('mm-dd-yyyy', 'MM-DD-YYYY'), ('yyyy-mm-dd', 'YYYY-MM-DD')], default='dd-mm-yyyy', max_length=20)),
                ('availability', models.CharField(choices=[('available', 'Available for Jobs'), ('busy', 'Busy - Limited Availability'), ('unavailable', 'Unavailable - On Break')], default='available', max_length=20)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_detail_table',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_availability_table',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='employee_certificates/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_certificate_table',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'employee_experience_table',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLogin',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_login_table',
            },
        ),
        migrations.CreateModel(
            name='EmployeeNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System Message'), ('profile', 'Profile Update'), ('security', 'Security Alert'), ('payment', 'Payment Update'), ('job', 'Job Update')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_notification_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePortfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='employee_portfolio/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_portfolio_table',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_skill_table',
            },
        ),
        migrations.CreateModel(
            name='JobAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('message', 'Message Sent')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_action_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('proposed_date', models.DateField()),
                ('proposed_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('asap', 'ASAP')], default='normal', max_length=20)),
                ('employer_notes', models.TextField(blank=True, null=True)),
                ('employee_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejection_message_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'job_request_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.FloatField(blank=True, help_text='Numerical rating (1-5 stars, optional)', null=True)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employee.employee')),
            ],
            options={
                'db_table': 'employee_review_table',
                'ordering': ['-created_at'],
            },
        ),
    ]
