# Generated by Django 4.2 on 2026-02-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_reviews', to='employer.employer'),
        ),
        migrations.AddField(
            model_name='review',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='employee.jobrequest'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='employer.employer'),
        ),
        migrations.AddField(
            model_name='jobaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AddField(
            model_name='jobaction',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.employer'),
        ),
        migrations.AddField(
            model_name='jobaction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='employee.jobrequest'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeeportfolio',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeenotification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeelogin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeecertificate',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employeeavailability',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_availability', to='employee.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('employer', 'employee', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('employee', 'skill_name')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeavailability',
            unique_together={('employee', 'date')},
        ),
    ]
