# Generated by Django 5.2.5 on 2026-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='rejection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
