# Generated by Django 4.2 on 2026-01-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='rejection_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
