# Generated by Django 5.2.5 on 2026-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_jobrequest_rejection_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='rejection_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhar_document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhar_upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='aadhar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
