# Generated by Django 5.2.5 on 2026-02-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_jobrequest_rejection_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_covers/'),
        ),
    ]
