# Generated by Django 4.2 on 2026-02-02 17:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('churn', 'User Churn Prediction'), ('booking', 'Booking Success Prediction'), ('revenue', 'Revenue Forecast'), ('recommendation', 'Service Recommendation'), ('matching', 'Worker-Employer Matching')], max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('algorithm', models.CharField(default='XGBoost', max_length=50)),
                ('model_file', models.FileField(upload_to='ml_models/xgboost/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pkl', 'joblib', 'model'])])),
                ('file_size', models.IntegerField(default=0)),
                ('features_file', models.FileField(blank=True, null=True, upload_to='ml_models/features/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json', 'csv'])])),
                ('training_date', models.DateField(default=django.utils.timezone.now)),
                ('training_data_size', models.IntegerField(default=0)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('precision_score', models.FloatField(blank=True, null=True)),
                ('recall_score', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('testing', 'Testing'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('n_estimators', models.IntegerField(default=100)),
                ('max_depth', models.IntegerField(default=6)),
                ('learning_rate', models.FloatField(default=0.3)),
                ('min_child_weight', models.IntegerField(default=1)),
                ('subsample', models.FloatField(default=1.0)),
                ('colsample_bytree', models.FloatField(default=1.0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_model_table',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('revenue_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_revenue_table',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_contact_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_fund_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('razorpay_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('razorpay_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='employee.employee')),
            ],
            options={
                'db_table': 'payout_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelTrainingData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_source', models.CharField(choices=[('user_data', 'User Data'), ('booking_data', 'Booking Data'), ('revenue_data', 'Revenue Data'), ('review_data', 'Review Data'), ('combined', 'Combined Data')], max_length=50)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='training_data/')),
                ('total_samples', models.IntegerField(default=0)),
                ('total_features', models.IntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('preprocessing_steps', models.JSONField(blank=True, default=list)),
                ('feature_columns', models.JSONField(blank=True, default=list)),
                ('target_column', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_data', to='admin_self.mlmodel')),
            ],
            options={
                'db_table': 'model_training_data_table',
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(choices=[('accuracy', 'Accuracy'), ('precision', 'Precision'), ('recall', 'Recall'), ('f1', 'F1 Score'), ('auc_roc', 'AUC-ROC'), ('mse', 'Mean Squared Error'), ('mae', 'Mean Absolute Error'), ('rmse', 'Root Mean Squared Error')], max_length=50)),
                ('split_type', models.CharField(choices=[('train', 'Training Set'), ('test', 'Testing Set'), ('validation', 'Validation Set'), ('cross_val', 'Cross Validation')], max_length=50)),
                ('metric_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='admin_self.mlmodel')),
            ],
            options={
                'db_table': 'model_performance_table',
            },
        ),
        migrations.CreateModel(
            name='DataCollectionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_type', models.CharField(choices=[('automatic', 'Automatic Collection'), ('manual', 'Manual Export'), ('scheduled', 'Scheduled Export')], max_length=50)),
                ('data_type', models.CharField(max_length=100)),
                ('records_collected', models.IntegerField(default=0)),
                ('file_size', models.IntegerField(default=0)),
                ('file_format', models.CharField(default='csv', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='data_exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_collection_log_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('commission_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.001, max_digits=5)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Calculated'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='employee.employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='employer.employer')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='employer.payment')),
            ],
            options={
                'db_table': 'commission_table',
                'ordering': ['-created_at'],
            },
        ),
    ]
