# Generated by Django 4.2 on 2026-02-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_self', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingdata',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Model accuracy score', null=True),
        ),
        migrations.AddField(
            model_name='modeltrainingdata',
            name='duration_seconds',
            field=models.FloatField(default=0.0, help_text='Training duration in seconds'),
        ),
    ]
