# Generated by Django 4.2 on 2026-02-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_self', '0002_modeltrainingdata_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltrainingdata',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='modeltrainingdata',
            name='duration_seconds',
        ),
    ]
